## 导入数据库
```
# 若没现成的库则创建一个
create database if not exists database_name default charset utf8 collate utf8_general_ci;


use database_name;

# 导入sql文件
source sql_file_path;
```

## 查询数据
### 基本查询
```
# 从表中取出特定列
select column_names from table_name;

# 取出表中所以列
select * from table_name;
```

### 条件查询  where
```
# 取出表中所有满足条件表达式的列, 类似python中的列表generator
select * from table_name where (not) cond1 and/or cond2;
```

### 排序   order by
```
# 取出数据, 按列1的大小升序或降续排列, 再按列2的, 默认升序
select column_names form table_name order by column_name1 desc/asc, column_name2;

```

### 分页查询    limit offset
```
# 查询第一行, limit 1指的是最多一条数据
select * from table_name limit 1;

# 最多三条数据, 从0号记录开始, 查询第二页只需要将offset换作3, 当offset的值超过总记录数会返回空.
select * from table_name limit 3 offset 0;

# 查询n到m行,   
select * from table_name limit n-1,m-n;

```

### 去重查询    distinct
```
# 取出一列中不重复的数据
select distinct column_name from table_name;

# 取出列1列2同时都不重复的数据
select distinct column_name1, column_name2 from table_name;
```

### 聚合查询 
查询可以聚合sql的内置函数
```
# 查询所有列的行数, 查询结果是一个二维表, num是给这个二维表设置的一个别名
select count(*) num from table_name;
```

### 分组查询 group by
```
# 对某列的数据进行分组, 同一组的数据会被分配到一块
select * from table_name group by column_name;
```

### 多表查询 
```
# 返回一个二维表, 行数为两表之积, 列数为两表之和
select * from table_name1, table_name2;

# 将两个表中的相同字段映射到不同字段
select 
    t1.id id1,
    t2.id id2,
from table_name1 t1, table_name2 t2;
```

### 连接查询  inner/outer join
```
# 将表1中没有的表2列拼接到取出的二维表中, 按表1中表2的id对齐, 
# inner join返回两表都有的记录, right/left/full outer join 分别返回 右表/左表/两表全部 都有的记录
select 
    t1.id1,
    t1.id2,
    t2.name
from table_name1 t1
inner join table_name2 t2
on t1.id2 = t2.id2
```

### 判断语句 case when then else end
Case函数只返回第一个符合条件的值
``` 
# 永远不会返回2
case when column_name_1 in (a,b) then 1,
     when column_name_1 in (a) then 2,
     else other_column end;
```


```
# 满足不同条件返回不同的值
select 
    case when int_column > 100 and int_column <= 200 then 1,
         when int_column > 200 then 2,
    else int_column > 500 end 3;
         
```

### 运算符
#### 比较运算符
|符号|功能
|:-:|:-:
| = | 等于 
|<=>|安全的等于, 当一个操作数为null返回0
|<>(!=)|不等于
|is null|是否为null
|is not null| 是否非null
|least|多个参数时返回最小
|greatest| 多个参数时返回最大
|between and|是否在区间内
|isnull| 同is null
|in| 同between and
|like| 通配符匹配
|regexp|正则匹配

#### 逻辑运算符
|符号|功能
|:-:|:-:
| not(!) | 逻辑非
|and(&&)| 逻辑与
|or(||)| 逻辑或
|xor| 逻辑异或


#### 位运算符
|符号|功能
|:-:|:-:
|&| 位与
|^|位异或
|<<|位左移
|>>|位右移
|~|位取反




|优先级|符号
|-|:-:
|  低|=(赋值),:=
|||xor
|||and,&&
|||not
|||between, case, when, then, else
|||=, <=>, >=, >=, >, <, <>, !=, is, likem regexp, in
|||&
|||<<, >>
|||-,+
|||*,/,%
|||^
| v|~
|  高|!


### 通配符
> %  通配符,  匹配一个或多个字符

```
# 找出ed结尾的数据
select * from table_name where column_name like '%ed';
```
> _  通配符, 匹配一个字符

### Having
having通常与group by一起使用，根据指定的条件过滤分组

如果不与group by一起，则跟where类似

区别在于having将过滤条件应用于每组分行，而where将过滤条件应用于每个单独的行

```

```